### PR TITLE
Improved sanity tests

### PR DESCRIPTION
**Pull request by miabbott**
The existing sanity test(s) have always felt lacking in terms of
functional tests that are executed.  This change attempts to improve
(or perhaps, replace) the existing sanity test(s).

This is the first cut at these types of tests.  The intent is to
expand the coverage of this set of tests to include additional tests
that are small and focused.  More complex functional tests can be
covered in separate playbooks which can be run after this.

Notable changes:
  - roles everywhere
  - hard commitment to Ansible version 2+
  - selectable Vagrant boxes for testing playbooks
  - verify that `/tmp` is functional after each reboot
  - verify that added users persist after upgrade
  - verify changes to `/etc` persist after upgrade
  - verify that directories/files in `/var` persist after
    upgrade/rollback
  - verify that users added after upgrade do not persist after
    rollback

### CODE REVIEW

**Comment by mnguyen-gh** [comment]
Looks good!

**Comment by miabbott** [comment]
Welp, time to merge.  One LGTM is good enough for government work.  :wink:

**Comment by miabbott** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7uTm47Fq&#x2F;330-3-expand-coverage-of-sanity-tests-to-include-user-etc-var-tests"> (3) Expand coverage of sanity tests to include user, &#x2F;etc, &#x2F;var tests</a>

**Comment by miabbott** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7MDJNni6&#x2F;32-create-test-case-s-to-verify-that-users-are-properly-migrated-after-upgrade-rollback"> Create test case(s) to verify that users are properly migrated after upgrade&#x2F;rollback</a>

**Comment by miabbott** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XUTN0Oai&#x2F;33-create-test-case-s-for-3-way-merge-of-etc-during-upgrade"> Create test case(s) for 3-way merge of &#x2F;etc during upgrade</a>

**Pull request merged**
