### PR TITLE
README.md: add package list to dashboard

### LINKED ISSUE #422: Add link to list of packages on dashboard
The dashboard is awesome. It'd be great if we could add another column with a link to the list of package NEVRAs in the tested version to make it easier to find out which versions were included.

(Or maybe just running an `rpm -qa` as part of the i-s-t to let it show up in the test logs?).

### PR DESCRIPTION
**Pull request by mike-nguyen**
The CI jobs now uploads a list of packages in the compose to s3 so
lets add it to the dashboard.  The link will be broken until the
improved sanity test is run.

Closes #422

### CODE REVIEW

**Comment by mike-nguyen** [comment]
You can see a preview of the dashboard at:
https://github.com/mike-nguyen/atomic-host-tests/tree/dashboard_pkgs

**Comment by miabbott** [comment]
@jlebon your wishes have been granted

**Comment by miabbott** [comment]
LGTM!  I know @jlebon wanted this, so I'd like to see him chime in on the look and feel

**Comment by mike-nguyen** [comment]
@miabbott I'm cool with that

**Comment by jlebon** [comment]
Awesome, thanks for this! LGTM!
@rh-atomic-bot r+ f62fb23

**Comment by miabbott** [comment]
Sadly we do not have any bots to do our merges.  We still merge by hand like cavemen.

**Pull request merged**
