### PR TITLE
introduce podman sanity checks

### LINKED ISSUE #378: add test cases for 'podman'
We are including `podman` in Fedora 28/Rawhide, so we should look at adding some test cases to the sanity test around `podman`.

Additionally, we should investigate if we can run the `docker` test suite we have using `podman`

### PR DESCRIPTION
**Pull request by miabbott**
`podman` is included in most (all?) of the AH streams that we are testing, so let's start making sure it works on Atomic Host.

This is a re-implementation of the `docker_pull_run_remove` role that uses `podman`.  It's slightly more comprehensive than the original role, but still very bare bones.

Closes #378

### CODE REVIEW

**Comment by miabbott** [comment]
There is an existing BZ or two about network access when using `podman run` that is going to bite us with this test.

I could add a separate tag that we could filter on or just wait until the BZs are fixed to merge this.

**Comment by mike-nguyen** [comment]
I'm okay with waiting for the BZs.  Can you copy the BZs here so when they're fixed, I can just re-run and merge this?

**Comment by miabbott** [comment]
@mike-nguyen my understanding is that we need this https://github.com/containernetworking/plugins/pull/75 merged and then we need a new build of `podman`

**Comment by mike-nguyen** [comment]
Is this temporarily fixed with this: https://github.com/containers/libpod/pull/1431 ?

**Comment by miabbott** [comment]
It *should* be; but we still have to wait for builds to land across all the platforms.

**Comment by miabbott** [comment]
bot, retest this please

**Comment by miabbott** [comment]
bot, retest this please

**Comment by miabbott** [comment]
CentOS is still going to fail because the build of `podman` is too old to have the fix for `--net=host`, but everything else should be OK.

**Comment by mike-nguyen** [comment]
@miabbott  I'm not too concerned about CentOS7.  CAHC seems to be failing pulling from registry.access.redhat.com because it doesn't have a cert.  If one is required can we put one in or just skip the r.a.rh.com test completely?

**Comment by miabbott** [comment]
Yeah, the root cause is here:

https://github.com/CentOS/sig-atomic-buildscripts/issues/329

I think there is still value in pulling from `registry.access.redhat.com`, so I'll further adjust the test to skip that registry on CAHC

**Comment by miabbott** [comment]
Just pushed a new commit with fixes.  :arrow_up: 

The CI checks are probably going to fail because OpenStack is bad and should feel bad.

**Comment by mike-nguyen** [comment]
Look, it worked!

**Comment by mike-nguyen** [comment]
LGTM!

**Pull request merged**
