### PR TITLE
Expand automated tests on PRs

### PR DESCRIPTION
**Pull request by miabbott**
Since we require that roles/tests work across multiple versions of
Atomic Host, we should start testing across multiple versions of
Atomic Host.

This change enables the running of the `improved-sanity-test` on a
Fedora 25 Atomic Host and CentOS 7 Atomic Host (which is pretty close
to a RHEL Atomic Host).

Granted, we are only running the sanity tests now, but hopefully we
can modify this to run new roles or tests in the future.

### CODE REVIEW

**Comment by jlebon** [comment]
This looks sane to me. 👍

**Comment by cgwalters** [comment]
Looks sane to me.

**Comment by miabbott** [comment]
Hey, the checks worked too!  ✔️

**Comment by mike-nguyen** [comment]
Nice!!

**Pull request merged**
