### PR TITLE
Improve error messages in roles

### PR DESCRIPTION
**Pull request by mike-nguyen**
Sometimes its not easy to figure out why a test failed based on
the error message.  Digging into the code to find the failure
comparison that caused the failure is required.

Lets make the error messages more detailed when comparisons are
made so triaging failures is easier.

Note: This commit is only improving the error messages in the roles.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
fedora/26/atomic failure is unrelated to this PR

**Comment by miabbott** [comment]
This looks like it will mostly address #239, right?

**Comment by mike-nguyen** [comment]
> This looks like it will mostly address #239, right?
Yes, I will do the actual tests next.

**Comment by miabbott** [comment]
I tried to get the `fedora/26/atomic` context to pass, but it looks like we are hitting the same condition that was addressed in #284 

I'll submit another PR for that issue, but this one is good to merge!  Thanks for cleaning this up.

**Pull request merged**
