### PR TITLE
docker-build-httpd:  set MTU equal to default interface

### PR DESCRIPTION
**Pull request by miabbott**
When running an OpenStack environment, the host under test might end
up with an MTU that doesn't jive with the Docker daemon (usually when
the MTU is lower than 1500).  This can lead to network issues when
doing `docker build`.  So we'll just set the MTU for the Docker
daemon to the same.

### CODE REVIEW

**Comment by jlebon** [comment]
I'd add a link to https://bugzilla.redhat.com/show_bug.cgi?id=1475460 somewhere in there. :)

**Comment by miabbott** [comment]
Huh...need to install `rsync` in the container running the test.  See #294

**Comment by mike-nguyen** [comment]
bot, retest this please

**Comment by mike-nguyen** [comment]
LGTM

**Pull request merged**
