### PR TITLE
README: remove F27 from dashboard; add F29-testing

### PR DESCRIPTION
**Pull request by miabbott**

### CODE REVIEW

**Comment by miabbott** [comment]
Rendered:  https://github.com/miabbott/atomic-host-tests/tree/f29_testing_readme

**Comment by jlebon** [comment]
Looks sane to me!
Time to delete the f27 jobs?

**Comment by miabbott** [comment]
>  Time to delete the f27 jobs?

They are already deleted from the configs in 4f1c23a; just need to manually delete them from the active jobs in Jenkins itself.

**Comment by miabbott** [comment]
> They are already deleted from the configs in 4f1c23a; just need to manually delete them from the active jobs in Jenkins itself.

@jlebon the F27 jobs are gone completely now  :)

**Pull request merged**
