### PR TITLE
roles: adapt to Rawhide == F29

### PR DESCRIPTION
**Pull request by miabbott**
We have to bump our $releasever for Rawhide now that F28 has branched,
which means Rawhide == F29.

I've added the necessary files to cover this change as well as
rearranged some things under `selinux_verify/vars` to make a little
more sense (I hope).

While I was mucking around in here, I continued to remove references
to older versions of Fedora (24,25) where possible.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
The code looks good to me but there's a failure in fedora/27/atomc with AVC denials.  It seems unrelated to the changes.

**Comment by miabbott** [comment]
> The code looks good to me but there's a failure in fedora/27/atomc with AVC denials. It seems unrelated to the changes.

Strange...our sanity tests should have caught that before now.  I'm going to retry that test to see what happens again.

**Comment by miabbott** [comment]
LOL...fixed it.  :laughing:

**Comment by mike-nguyen** [comment]
:+1:  Merging!

**Pull request merged**
