### PR TITLE
Change to more complex rpm-ostree install package

### PR DESCRIPTION
**Pull request by mike-nguyen**
A new feature was added to allow non-root packages to be layered
using rpm-ostree install.  Instead of using a simple package like
wget, the httpd package  tests a broader code path because it has
multiple dependencies, creates an apache user, and is a non root
package.

The default settings for httpd conflicted with the docker container
tests in improved sanity tests so it was changed to port 8080 in the
httpd_start role.  The httpd service is validated by retrieving the
default apache page.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
Note:  The improved sanity test will not pass unless the starting version contains rpm-ostree support for layering non-root packages.

**Comment by cgwalters** [comment]
It should be possible to use the new [YAML --version](https://github.com/projectatomic/rpm-ostree/pull/665) to conditionalize (if `--version` doesn't output YAML it's too old).

**Comment by mike-nguyen** [comment]
@cgwalters That'll be really useful when all the streams get the newer versions

**Comment by miabbott** [comment]
LGTM.  I'll wait on merging based on the comment here - https://trello.com/c/LjwJQYOV/663-5-expand-rpm-ostree-package-layering-tests-in-a-h-t-to-cover-more-scenarios#action-58cb1aba8278356e5f83d321

**Comment by cgwalters** [comment]
It should be pretty easy to check whether or not `rpm-ostree --version` is YAML; one approach is to check whether the first line of output has a `:`.  Then treat the non-YAML case as "older than v2017.4".

**Comment by mike-nguyen** [comment]
bot, retest this please

**Comment by miabbott** [comment]
[(5) Expand rpm-ostree package layering tests in [a-h-t] to cover more scenarios](https://trello.com/c/LjwJQYOV/663-5-expand-rpm-ostree-package-layering-tests-in-a-h-t-to-cover-more-scenarios)

**Comment by miabbott** [comment]
LGMT! 👍

**Pull request merged**
