### PR TITLE
repo: add .redhat-ci.yml

### PR DESCRIPTION
**Pull request by jlebon**
Now that we have a known working tree with the CAHC smoketested branch,
we can spin this around and use it to automatically test new additions
to the improved sanity tests.

Of course, if we're adding new tests that catch bugs that are already
present in the latest smoketested branch, the PR tester will fail. Thus,
this is not meant to be used with a merge bot, but rather a general
indication of how sane a PR is.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
:+1:

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
OK, let's put this on hold for now. Apparently, it's a [very](https://github.com/ansible/ansible/issues/14426) [common](https://github.com/ansible/ansible/issues/13278) [issue](https://github.com/ansible/ansible/issues/14020). There's a cornucopia of workarounds in those issues, but I'd like to take a closer look before trying anything.

**Comment by miabbott** [comment]
@jlebon Where are we at with this?  Do we think the problems were related to the infra?

**Comment by jlebon** [comment]
@miabbott We're about to find out :)

**Comment by jlebon** [comment]
✔️

**Comment by miabbott** [comment]
Awesome!  Let's merge it!

**Comment by mike-nguyen** [comment]
:1st_place_medal:

**Pull request merged**
