### PR TITLE
Move away from deprecated docker module

### PR DESCRIPTION
**Pull request by ashcrow**
The docker module is now considered deprecated. This change moves to
using the newer docker_container (2.1.0) and docker_image (1.5)
modules.

See: http://docs.ansible.com/ansible/docker_module.html#deprecated

Part of #28

### CODE REVIEW

**Comment by miabbott** [comment]
@mike-nguyen A wild PR appears!  This LGTM, but would like you to have a peek, too.

**Comment by mike-nguyen** [comment]
Tested locally and it LGTM.

**Comment by mike-nguyen** [comment]
I tested with the test that doesn't use these roles and will need to revert this merge. :cry:

**Comment by ashcrow** [comment]
@mike-nguyen what was the issue found?

**Comment by mike-nguyen** [comment]
@ashcrow we actually pin to Ansible version 2.1 for the tests because of the constant changes in the modules (mostly docker).  This provides more stability and maintainability for CI.  Since the changes for the docker module are in the newer version, it fails in 2.1.

**Comment by ashcrow** [comment]
@mike-nguyen doh. Sorry guys :frowning_man:

**Comment by mike-nguyen** [comment]
@aschrow not your fault!  I tested the wrong test suite that doesn't execute the roles you modified then merged it.  I should have caught it before I merged it. :disappointed:

**Pull request merged**
