### PR TITLE
README: remove Fedora 25 results

### PR DESCRIPTION
**Pull request by miabbott**
We've stopped testing Fedora 25 on our internal infra, so we can
remove these results from the dashboard.

### CODE REVIEW

**Comment by jlebon** [comment]
Maybe let's drop it from `.papr.yml` as well?

**Comment by miabbott** [comment]
> Maybe let's drop it from .papr.yml as well?

Doh!  Will do

**Comment by jlebon** [comment]
LGTM! 👍

**Comment by mike-nguyen** [comment]
LGTM also!

**Pull request merged**
